# Generated by Django 5.2.6 on 2025-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aspirantes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='caracterizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='carta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='max_inscripciones',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='curso',
            name='pdf_documentos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firma/'),
        ),
    ]
