# Generated by Django 5.1.3 on 2025-09-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='version',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
