# Generated by Django 5.2.6 on 2025-09-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=191, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Población',
                'verbose_name_plural': 'Poblaciones',
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='aspirantes',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='caracterizacion',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carta',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='pdf_documentos',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=191, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=191, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('documento', models.CharField(max_length=191, unique=True, verbose_name='Documento')),
                ('archivo_documento', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo Documento')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='curso.curso')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='curso.tipodocumento')),
                ('poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='curso.poblacion')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
            },
        ),
    ]
