# Generated by Django 5.2.6 on 2025-09-19 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_aspirantes_curso_caracterizacion_curso_carta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='firma',
        ),
        migrations.AddField(
            model_name='usuario',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
