# Generated by Django 5.1.3 on 2025-09-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_aspirantes_curso_caracterizacion_curso_carta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Población',
                'verbose_name_plural': 'Poblaciones',
            },
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='Documento')),
                ('archivo_documento', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo Documento')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='curso.curso')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='curso.tipodocumento')),
                ('poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='curso.poblacion')),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
            },
        ),
    ]
