# Generated by Django 5.1.3 on 2025-09-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_programa_version_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aspirantes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='caracterizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='carta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='pdf_documentos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
