# Generated by Django 5.2.6 on 2025-09-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_aspirantes_curso_caracterizacion_curso_carta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='curso.estado'),
        ),
    ]
