# Generated by Django 5.2.6 on 2025-09-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_estado_alter_curso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firma/'),
        ),
    ]
